DROP TABLE BURGER_ORDER CASCADE CONSTRAINTS;
DROP TABLE BURGER_MENU CASCADE CONSTRAINTS;
DROP TABLE BURGER_STOCK CASCADE CONSTRAINTS;
DROP SEQUENCE  SEQ_ORDERNO;

CREATE TABLE BURGER_MENU(
    MENU_NO NUMBER,
    MENU_NAME VARCHAR2(30) CONSTRAINT NNMENU_NAME NOT NULL,
    PRICE NUMBER CONSTRAINT NNPRICE NOT NULL
);

COMMENT ON COLUMN BURGER_MENU.MENU_NO IS '메뉴번호';
COMMENT ON COLUMN BURGER_MENU.MENU_NAME IS '메뉴이름';
COMMENT ON COLUMN BURGER_MENU.PRICE IS '가격';

ALTER TABLE BURGER_MENU ADD CONSTRAINT PKMENU_NO PRIMARY KEY (MENU_NO);

CREATE TABLE BURGER_ORDER(
    ORDER_NO NUMBER,
    MENU_NO NUMBER,
    ORDER_QTY NUMBER,
    CUSTOMER_NAME VARCHAR2(20) CONSTRAINT NN_CUSTOMER NOT NULL,
    PHONE VARCHAR2(13),
    ORDER_DATE VARCHAR2(30) DEFAULT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS'),
    ORDER_SHOP CHAR(2) DEFAULT 'Y' CONSTRAINT NN_SHOP NOT NULL,
    POINT NUMBER DEFAULT 0.3
);



CREATE SEQUENCE SEQ_ORDERNO
START WITH 1
INCREMENT BY 1
MAXVALUE 999
CYCLE
NOCACHE;

COMMENT ON COLUMN BURGER_ORDER.ORDER_NO IS '주문번호';
COMMENT ON COLUMN BURGER_ORDER.MENU_NO IS '메뉴번호';
COMMENT ON COLUMN BURGER_ORDER.ORDER_QTY IS '메뉴수량';
COMMENT ON COLUMN BURGER_ORDER.CUSTOMER_NAME IS '고객명';
COMMENT ON COLUMN BURGER_ORDER.PHONE IS '전화번호';
COMMENT ON COLUMN BURGER_ORDER.ORDER_DATE IS '주문일자';
COMMENT ON COLUMN BURGER_ORDER.ORDER_SHOP IS '매장/포장';
COMMENT ON COLUMN BURGER_ORDER.POINT IS '적립포인트';

ALTER TABLE BURGER_ORDER ADD CONSTRAINT PKORDER_NO PRIMARY KEY (ORDER_NO, MENU_NO, ORDER_DATE);
ALTER TABLE BURGER_ORDER ADD CONSTRAINT CKPOINT CHECK (POINT >=0 AND POINT<=1.0);
ALTER TABLE BURGER_ORDER ADD CONSTRAINT CKQTY CHECK (ORDER_QTY>0);
ALTER TABLE BURGER_ORDER ADD CONSTRAINT FKMENU_NO FOREIGN KEY (MENU_NO) REFERENCES BURGER_MENU (MENU_NO);



CREATE TABLE BURGER_STOCK(
    STOCK_NO NUMBER,
    STOCK_NAME VARCHAR2(30),
    STOCK_QTY NUMBER,
    MENU_NO NUMBER
);
COMMENT ON COLUMN BURGER_STOCK.STOCK_NO IS '재고번호';
COMMENT ON COLUMN BURGER_STOCK.STOCK_NAME IS '재고이름';
COMMENT ON COLUMN BURGER_STOCK.STOCK_QTY IS '재고수량';
COMMENT ON COLUMN BURGER_STOCK.MENU_NO IS '메뉴번호';

ALTER TABLE BURGER_STOCK ADD CONSTRAINT PKSTOCK_NO PRIMARY KEY (STOCK_NO, MENU_NO);
ALTER TABLE BURGER_STOCK ADD CONSTRAINT FKSMENU_NO FOREIGN KEY (MENU_NO) REFERENCES BURGER_MENU (MENU_NO);


INSERT ALL 
INTO BURGER_MENU VALUES(1,'치즈버거',3000)
INTO BURGER_MENU VALUES(2,'불고기버거',3500)
INTO BURGER_MENU VALUES(3,'치킨버거',4500)
INTO BURGER_MENU VALUES(4,'콜라',1500)
INTO BURGER_MENU VALUES(5,'사이다',1500)
INTO BURGER_MENU VALUES(6,'후렌치후라이',1200)
INTO BURGER_STOCK VALUES(1,'고기패티',50,2)
INTO BURGER_STOCK VALUES(2,'치킨패티',50,3)
INTO BURGER_STOCK VALUES(3,'치즈',50,1)
INTO BURGER_STOCK VALUES(4,'콜라',50,4)
INTO BURGER_STOCK VALUES(5,'사이다',50,5)
INTO BURGER_STOCK VALUES(6,'감자',50,6)
INTO BURGER_STOCK VALUES(7,'양상추',300,1)
INTO BURGER_STOCK VALUES(7,'양상추',300,2)
INTO BURGER_STOCK VALUES(7,'양상추',300,3)
INTO BURGER_STOCK VALUES(8,'빵',300,1)
INTO BURGER_STOCK VALUES(8,'빵',300,2)
INTO BURGER_STOCK VALUES(8,'빵',300,3)
SELECT * FROM DUAL;

COMMIT;